# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
	# check these on https://fabricmc.net/develop/
	minecraft_version=1.21.8
	minecraft_version_dependency=>=1.21.6 <=1.21.8
	minecraft_version_list=1.21.6,1.21.7,1.21.8
	minecraft_version_list_presentable=1.21.6 - 1.21.8
	loader_version=0.17.2
	loom_version=1.11-SNAPSHOT

	# check these on https://maven.parchmentmc.org/org/parchmentmc/data/
	parchment_mcversion=1.21.8
	parchment_version=2025.07.20

# Mod Properties
	mod_version=2.11.3
	maven_group=net.earthcomputer
	archives_base_name=clientcommands

# Dependencies
	# also check this on https://fabricmc.net/develop/
	fabric_version=0.131.0+1.21.8
	clientarguments_version=1.11.4
	betterconfig_version=2.4.0
	simplewaypoints_version=1.0.0-alpha.4
	seedfinding_core_version=1.210.0
	seedfinding_biome_version=1.171.1
	seedfinding_feature_version=1.171.11
	seedfinding_seed_version=1.171.2
	latticg_version=1.07
	mapping_io_version=0.7.1
	devauth_version=1.2.1
	checkstyle_version=11.0.0

	jazzer_junit_version=0.24.0
	junit_version=5.13.4
