name: Check Build
on:
  pull_request:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew build --stacktrace --no-daemon
